[ ("end", "end.html")
, ("jumbostart", "jumbostart.html")
, ("jumbologo", "jumbologo.html")
, ("row", "row.html")
, ("halfbox", "halfbox.html")
, ("centering", "centering.html")
, ("sidenav", "sidenav.html")
, ("nomobile", "nomobile.html")
, ("onlymobile", "onlymobile.html")
]
